### ISSUE TITLE
Add an space between the author and the category

### ISSUE THREAD

**Issue by Poliuk** [worona/starter-app-theme-worona#15]
![screen shot 2017-02-21 at 19 41 20](https://cloud.githubusercontent.com/assets/2798729/23179330/c5ee0750-f86d-11e6-9a61-eec46c50378a.png)

**Comment by luisherranz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [asfas](https://trello.com/c/Vo5YVh8Y/1-asfas)
