### ISSUE TITLE
The App displays only the first 10 categories.

### ISSUE THREAD

**Issue by Poliuk** [worona/starter-app-theme-worona#17]
**URL:** https://www.emarketing.pl
**Site ID:** 9kRFALiwWpCpFg2TY

The site has 16 categories (https://www.emarketing.pl/wp-json/wp/v2/categories?per_page=16) but it is displaying only 10 inside the App.

**Comment by Poliuk** [comment]
Another affected site:

**URL:** http://www.kashmirreader.com
**SiteId:** eEKeMG3ErqAzcFs6i

**Comment by tohaitrieu** [comment]
Another site:

Url: https://isach.net
SiteID: L6N32kNWRiN7wpozJ
